import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import Headbar from "./Headbar";
import QueryClientProvider from "./QueryClientProvider";
import { Toaster } from "sonner";
import { BookmarkProvider } from "@/components/bookmarks/context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryClientProvider>
          <BookmarkProvider>
            <SidebarProvider>
              <Navbar variant="inset" />
              <SidebarInset>
                <Toaster richColors />
                <Headbar />
                <main className="flex flex-1 flex-col gap-4 p-4">
                  {children}
                </main>
              </SidebarInset>
            </SidebarProvider>
          </BookmarkProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
